In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv("Smart_Outcome_Predictor_Dataset_5200 - Smart_Outcome_Predictor_Dataset_5200.csv.csv")
df

,student_id,age,country_region,device_type,education_background,course_level,course_category,course_start_date,week_of_year,sessions,time_spent_hours,videos_watched,quiz_attempts,assignments_submitted,forum_posts,avg_quiz_score,attendance_rate,completion_status,final_score
0,700001,32,Europe,Laptop,Undergrad,Intermediate,Business,2024-03-18,12,1,7.6,1,6,1,1,53.3,0.655,0,49.8
1,700002,17,Europe,Laptop,Undergrad,Intermediate,Programming,2024-08-22,34,16,27.2,6,4,7,1,51.5,1.000,1,84.0
2,700003,25,Europe,Mobile,Graduate,Advanced,Programming,2024-09-28,39,6,7.1,16,2,2,0,62.2,0.810,0,62.5
3,700004,26,Asia,Mobile,Undergrad,Beginner,Design,2024-03-09,10,34,22.1,57,9,6,0,59.3,0.875,1,89.5
4,700005,26,Asia,Tablet,WorkingPro,Advanced,Business,2024-03-21,12,22,32.3,41,9,2,0,65.1,0.814,0,67.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5195,705196,28,Asia,Tablet,WorkingPro,Advanced,Data,2024-08-26,35,27,26.1,28,7,8,1,77.2,0.897,1,97.4
5196,705197,28,Africa,Tablet,Graduate,Beginner,Design,2024-04-27,17,21,3.9,31,8,4,0,82.4,0.743,1,71.9
5197,705198,22,Asia,Laptop,Undergrad,Intermediate,Marketing,2024-08-01,31,32,12.8,43,7,2,0,62.4,0.757,1,71.5
5198,705199,25,Asia,Laptop,Graduate,Beginner,Programming,2024-01-18,3,16,27.1,21,5,8,2,76.1,0.847,0,86.8
5199,705200,26,Europe,Mobile,HighSchool,Intermediate,Data,2024-12-24,52,20,28.8,37,11,5,3,NaN,0.768,0,67.9

In [5]:
df.shape

(5200, 19)

In [6]:
df.head()

,student_id,age,country_region,device_type,education_background,course_level,course_category,course_start_date,week_of_year,sessions,time_spent_hours,videos_watched,quiz_attempts,assignments_submitted,forum_posts,avg_quiz_score,attendance_rate,completion_status,final_score
0,700001,32,Europe,Laptop,Undergrad,Intermediate,Business,2024-03-18,12,1,7.6,1,6,1,1,53.3,0.655,0,49.8
1,700002,17,Europe,Laptop,Undergrad,Intermediate,Programming,2024-08-22,34,16,27.2,6,4,7,1,51.5,1.000,1,84.0
2,700003,25,Europe,Mobile,Graduate,Advanced,Programming,2024-09-28,39,6,7.1,16,2,2,0,62.2,0.810,0,62.5
3,700004,26,Asia,Mobile,Undergrad,Beginner,Design,2024-03-09,10,34,22.1,57,9,6,0,59.3,0.875,1,89.5
4,700005,26,Asia,Tablet,WorkingPro,Advanced,Business,2024-03-21,12,22,32.3,41,9,2,0,65.1,0.814,0,67.4

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5200 entries, 0 to 5199
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   student_id             5200 non-null   int64
 1   age                    5200 non-null   int64
 2   country_region         5200 non-null   object
 3   device_type            5200 non-null   object
 4   education_background   5200 non-null   object
 5   course_level           5200 non-null   object
 6   course_category        5200 non-null   object
 7   course_start_date      5200 non-null   object
 8   week_of_year           5200 non-null   int64
 9   sessions               5200 non-null   int64
 10  time_spent_hours       5088 non-null   float64
 11  videos_watched         5200 non-null   int64
 12  quiz_attempts          5200 non-null   int64
 13  assignments_submitted  5200 non-null   int64
 14  forum_posts            5200 non-null   int64
 15  avg_quiz_score         5119 non-null   float64
 16  attendance_rate        5120 non-null   float64
 17  completion_status      5200 non-null   int64
 18  final_score            5200 non-null   float64
dtypes: float64(4), int64(9), object(6)
memory usage: 772.0+ KB

In [8]:
df.describe()

,student_id,age,week_of_year,sessions,time_spent_hours,videos_watched,quiz_attempts,assignments_submitted,forum_posts,avg_quiz_score,attendance_rate,completion_status,final_score
count,5200.000000,5200.000000,5200.000000,5200.000000,5088.000000,5200.000000,5200.000000,5200.000000,5200.000000,5119.000000,5120.000000,5200.000000,5200.000000
mean,702600.500000,24.339615,26.621538,19.121923,18.216156,25.852885,6.995769,3.835769,1.585577,66.842626,0.847189,0.375385,74.821615
std,1501.255031,5.578864,15.007731,10.726708,10.734114,17.720493,2.568017,1.951802,1.270640,13.813992,0.113545,0.484269,13.531829
min,700001.000000,16.000000,1.000000,1.000000,0.600000,0.000000,0.000000,0.000000,0.000000,0.000000,0.313000,0.000000,35.200000
25%,701300.750000,20.000000,14.000000,11.000000,10.300000,13.000000,5.000000,2.000000,1.000000,57.500000,0.768750,0.000000,64.700000
50%,702600.500000,24.000000,27.000000,17.000000,16.100000,23.000000,7.000000,4.000000,1.000000,66.900000,0.855000,0.000000,74.100000
75%,703900.250000,28.000000,40.000000,25.000000,23.800000,35.000000,9.000000,5.000000,2.000000,76.200000,0.942000,1.000000,84.900000
max,705200.000000,45.000000,52.000000,94.000000,76.800000,158.000000,20.000000,12.000000,8.000000,100.000000,1.000000,1.000000,100.000000

In [9]:
df.isnull().sum()

student_id                 0
age                        0
country_region             0
device_type                0
education_background       0
course_level               0
course_category            0
course_start_date          0
week_of_year               0
sessions                   0
time_spent_hours         112
videos_watched             0
quiz_attempts              0
assignments_submitted      0
forum_posts                0
avg_quiz_score            81
attendance_rate           80
completion_status          0
final_score                0
dtype: int64

In [10]:
# Numerical columns
num_cols = df.select_dtypes(include=['int64', 'float64']).columns
# Categorical columns
cat_cols = df.select_dtypes(include=['object']).columns
print("Numerical Columns:", num_cols)
print("Categorical Columns:", cat_cols)

Numerical Columns: Index(['student_id', 'age', 'week_of_year', 'sessions', 'time_spent_hours',
       'videos_watched', 'quiz_attempts', 'assignments_submitted',
       'forum_posts', 'avg_quiz_score', 'attendance_rate', 'completion_status',
       'final_score'],
      dtype='object')
Categorical Columns: Index(['country_region', 'device_type', 'education_background', 'course_level',
       'course_category', 'course_start_date'],
      dtype='object')

In [11]:
from sklearn.impute import SimpleImputer
sl = SimpleImputer(strategy="mean")
data = df.copy()
data[num_cols] = sl.fit_transform(data[num_cols])

In [12]:
data.isnull().sum()

student_id               0
age                      0
country_region           0
device_type              0
education_background     0
course_level             0
course_category          0
course_start_date        0
week_of_year             0
sessions                 0
time_spent_hours         0
videos_watched           0
quiz_attempts            0
assignments_submitted    0
forum_posts              0
avg_quiz_score           0
attendance_rate          0
completion_status        0
final_score              0
dtype: int64

In [13]:
from sklearn.preprocessing import LabelEncoder, StandardScaler
df_le = data.copy()
encoder = LabelEncoder()
for col in cat_cols:
    df_le[col] = encoder.fit_transform(df_le[col])

In [14]:
X = df_le.drop(columns=["student_id","final_score","completion_status"])
# Classfication Target
y_class = df_le["completion_status"]
# Regression Target
y_reg = df_le["final_score"]

In [15]:
# Classification
from sklearn.model_selection import train_test_split
X_train_cls, X_test_cls, y_train_cls, y_test_cls = train_test_split(X,y_class,random_state=42,test_size=0.2)

In [16]:
print("Classification Train Shape:",X_train_cls.shape)
print("Classification Test Shape:",X_test_cls.shape)

Classification Train Shape: (4160, 16)
Classification Test Shape: (1040, 16)

In [17]:
# Regression 
X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(X,y_reg,random_state=42,test_size=0.2)

In [18]:
print("Regression Train Shape :", X_train_reg.shape)
print("Regression Test Shape :", X_test_reg.shape)

Regression Train Shape : (4160, 16)
Regression Test Shape : (1040, 16)

In [19]:
from sklearn.preprocessing import LabelEncoder, StandardScaler
df2 = df.copy()
encoder = LabelEncoder()
categorical_columns = [
    "country_region",
    "device_type",
    "education_background",
    "course_level",
    "course_category",
    "course_start_date"
]
for col in categorical_columns:
    df2[col] = encoder.fit_transform(df2[col])

In [20]:
X = df2.drop(["completion_status", "final_score"], axis=1)

y_class = df2["completion_status"]
y_reg = df2["final_score"]

In [ ]:
X_train_cls, X_test_cls, y_train_cls, y_test_cls = train_test_split(X, y_class,test_size=0.2,random_state=42)

In [ ]:
X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(X, y_reg,test_size=0.2,random_state=42)

In [23]:
scaler = StandardScaler()

X_train_cls = scaler.fit_transform(X_train_cls)
X_test_cls = scaler.transform(X_test_cls)

X_train_reg = scaler.fit_transform(X_train_reg)
X_test_reg = scaler.transform(X_test_reg)

print("Preprocessing Completed Successfully!")

Preprocessing Completed Successfully!

# PART : C

In [24]:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [25]:
bag_cls = BaggingClassifier(
    estimator=DecisionTreeClassifier(),
    n_estimators=10,
    random_state=42
)

# Train Model
bag_cls.fit(X_train_cls, y_train_cls)

# Prediction
y_pred_cls = bag_cls.predict(X_test_cls)

# Accuracy
print("Bagging Classifier Accuracy:", accuracy_score(y_test_cls, y_pred_cls))

Bagging Classifier Accuracy: 0.6788461538461539

In [26]:
from sklearn.ensemble import BaggingRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error, r2_score

In [27]:
# Create Model
bag_reg = BaggingRegressor(
    estimator=DecisionTreeRegressor(),
    n_estimators=10,
    random_state=42
)

# Train Model
bag_reg.fit(X_train_reg, y_train_reg)

# Prediction
y_pred_reg = bag_reg.predict(X_test_reg)

# Evaluation
print("R2 Score:", r2_score(y_test_reg, y_pred_reg))
print("MSE:", mean_squared_error(y_test_reg, y_pred_reg))

R2 Score: 0.4141829928871321
MSE: 109.4537939423077

In [28]:
from sklearn.tree import DecisionTreeClassifier

# Single Decision Tree
tree_cls = DecisionTreeClassifier(random_state=42)
tree_cls.fit(X_train_cls, y_train_cls)

tree_pred = tree_cls.predict(X_test_cls)

print("Decision Tree Accuracy :", accuracy_score(y_test_cls, tree_pred))
print("Bagging Accuracy       :", accuracy_score(y_test_cls, y_pred_cls))

Decision Tree Accuracy : 0.6230769230769231
Bagging Accuracy       : 0.6788461538461539

In [29]:
from sklearn.tree import DecisionTreeRegressor

# Single Decision Tree
tree_reg = DecisionTreeRegressor(random_state=42)
tree_reg.fit(X_train_reg, y_train_reg)

tree_pred_reg = tree_reg.predict(X_test_reg)

print("Decision Tree R2 :", r2_score(y_test_reg, tree_pred_reg))
print("Bagging R2       :", r2_score(y_test_reg, y_pred_reg))

Decision Tree R2 : -0.12440426377668268
Bagging R2       : 0.4141829928871321

In [30]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='mean')

X_train_cls = imputer.fit_transform(X_train_cls)
X_test_cls = imputer.transform(X_test_cls)
X_train_reg = imputer.transform(X_train_reg)
X_test_reg = imputer.transform(X_test_reg)

# PART : D

In [31]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import accuracy_score

# Create Model
ada_cls = AdaBoostClassifier(
    n_estimators=50,
    random_state=42
)

# Train
ada_cls.fit(X_train_cls, y_train_cls)

# Predict
y_pred_ada_cls = ada_cls.predict(X_test_cls)

# Accuracy
print("AdaBoost Accuracy:", accuracy_score(y_test_cls, y_pred_ada_cls))

AdaBoost Accuracy: 0.7211538461538461

In [32]:
from sklearn.ensemble import AdaBoostRegressor
from sklearn.metrics import r2_score, mean_squared_error

# Create Model
ada_reg = AdaBoostRegressor(
    n_estimators=50,
    random_state=42
)

# Train
ada_reg.fit(X_train_reg, y_train_reg)

# Predict
y_pred_ada_reg = ada_reg.predict(X_test_reg)

# Evaluation
print("R2 Score:", r2_score(y_test_reg, y_pred_ada_reg))
print("MSE:", mean_squared_error(y_test_reg, y_pred_ada_reg))

R2 Score: 0.40470576714874573
MSE: 111.22451466314573

AdaBoost trains multiple weak learners one after another.

• Each new model focuses more on the previous mistakes.
• Wrong predictions get higher importance.
• This gradually improves the overall accuracy.

In [33]:
from sklearn.ensemble import GradientBoostingClassifier

# Create Model
gb_cls = GradientBoostingClassifier(
    n_estimators=100,
    learning_rate=0.1,
    random_state=42
)

# Train
gb_cls.fit(X_train_cls, y_train_cls)

# Predict
y_pred_gb_cls = gb_cls.predict(X_test_cls)

# Accuracy
print("Gradient Boosting Accuracy:", accuracy_score(y_test_cls, y_pred_gb_cls))

Gradient Boosting Accuracy: 0.7153846153846154

In [34]:
from sklearn.ensemble import GradientBoostingRegressor

# Create Model
gb_reg = GradientBoostingRegressor(
    n_estimators=100,
    learning_rate=0.1,
    random_state=42
)

# Train
gb_reg.fit(X_train_reg, y_train_reg)

# Predict
y_pred_gb_reg = gb_reg.predict(X_test_reg)

# Evaluation
print("R2 Score:", r2_score(y_test_reg, y_pred_gb_reg))
print("MSE:", mean_squared_error(y_test_reg, y_pred_gb_reg))

R2 Score: 0.48287595365349745
MSE: 96.61923113221815

• Learning Rate controls how much each tree learns.

• Smaller learning rate gives better accuracy but takes more time.

• More estimators usually improve performance but increase training time.

In [38]:
from lightgbm import LGBMClassifier

# Create Model
lgb_cls = LGBMClassifier(random_state=42)

# Train
lgb_cls.fit(X_train_cls, y_train_cls)

# Predict
y_pred_lgb_cls = lgb_cls.predict(X_test_cls)

# Accuracy
print("LightGBM Accuracy:", accuracy_score(y_test_cls, y_pred_lgb_cls))

[LightGBM] [Info] Number of positive: 1559, number of negative: 2601
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000287 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1562
[LightGBM] [Info] Number of data points in the train set: 4160, number of used features: 17
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.374760 -> initscore=-0.511851
[LightGBM] [Info] Start training from score -0.511851
LightGBM Accuracy: 0.698076923076923

C:\Users\lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

In [37]:
from lightgbm import LGBMRegressor

# Create Model
lgb_reg = LGBMRegressor(random_state=42)

# Train
lgb_reg.fit(X_train_reg, y_train_reg)

# Predict
y_pred_lgb_reg = lgb_reg.predict(X_test_reg)

# Evaluation
print("R2 Score:", r2_score(y_test_reg, y_pred_lgb_reg))
print("MSE:", mean_squared_error(y_test_reg, y_pred_lgb_reg))

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000214 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1562
[LightGBM] [Info] Number of data points in the train set: 4160, number of used features: 17
[LightGBM] [Info] Start training from score 74.774183
R2 Score: 0.4590787156306845
MSE: 101.06549669863108

C:\Users\lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

LightGBM is faster than AdaBoost and Gradient Boosting.
It trains efficiently on large datasets and usually gives high accuracy with less training time.

In [41]:
from xgboost import XGBClassifier

# Create Model
xgb_cls = XGBClassifier(
    random_state=42,
    eval_metric='logloss'
)

# Train
xgb_cls.fit(X_train_cls, y_train_cls)

# Predict
y_pred_xgb_cls = xgb_cls.predict(X_test_cls)

# Accuracy
print("XGBoost Accuracy:", accuracy_score(y_test_cls, y_pred_xgb_cls))

XGBoost Accuracy: 0.6961538461538461

In [42]:
from xgboost import XGBRegressor

# Create Model
xgb_reg = XGBRegressor(random_state=42)

# Train
xgb_reg.fit(X_train_reg, y_train_reg)

# Predict
y_pred_xgb_reg = xgb_reg.predict(X_test_reg)

# Evaluation
print("R2 Score:", r2_score(y_test_reg, y_pred_xgb_reg))
print("MSE:", mean_squared_error(y_test_reg, y_pred_xgb_reg))

R2 Score: 0.41660021583154216
MSE: 109.00216106231672

Among all boosting algorithms, XGBoost and LightGBM generally provide the best performance.
LightGBM trains faster, while XGBoost is more robust and often achieves slightly better accuracy.
AdaBoost is the simplest, and Gradient Boosting provides a good balance between speed and accuracy.

# PART : E

In [43]:
from sklearn.ensemble import VotingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [44]:
# Base Models
dt = DecisionTreeClassifier(random_state=42)
lr = LogisticRegression(max_iter=1000)
knn = KNeighborsClassifier()

# Voting Classifier
vote = VotingClassifier(
    estimators=[
        ('dt', dt),
        ('lr', lr),
        ('knn', knn)
    ],
    voting='hard'
)

# Train
vote.fit(X_train_cls, y_train_cls)

# Predict
y_pred_vote = vote.predict(X_test_cls)

print("Voting Accuracy:", accuracy_score(y_test_cls, y_pred_vote))

Voting Accuracy: 0.6961538461538461

In [45]:
# Hard Voting
hard = VotingClassifier(
    estimators=[('dt', dt), ('lr', lr), ('knn', knn)],
    voting='hard'
)

hard.fit(X_train_cls, y_train_cls)

# Soft Voting
soft = VotingClassifier(
    estimators=[('dt', dt), ('lr', lr), ('knn', knn)],
    voting='soft'
)

soft.fit(X_train_cls, y_train_cls)

print("Hard Voting :", accuracy_score(y_test_cls, hard.predict(X_test_cls)))
print("Soft Voting :", accuracy_score(y_test_cls, soft.predict(X_test_cls)))

Hard Voting : 0.6961538461538461
Soft Voting : 0.6826923076923077

Hard Voting selects the class with the most votes.

Soft Voting averages prediction probabilities and usually gives better accuracy.

In [46]:
from sklearn.ensemble import StackingClassifier

stack_cls = StackingClassifier(
    estimators=[
        ('dt', DecisionTreeClassifier()),
        ('knn', KNeighborsClassifier())
    ],
    final_estimator=LogisticRegression(max_iter=1000)
)

stack_cls.fit(X_train_cls, y_train_cls)

y_pred_stack = stack_cls.predict(X_test_cls)

print("Stacking Accuracy:", accuracy_score(y_test_cls, y_pred_stack))

Stacking Accuracy: 0.6682692307692307

In [47]:
from sklearn.ensemble import StackingRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import r2_score

In [48]:
stack_reg = StackingRegressor(
    estimators=[
        ('dt', DecisionTreeRegressor()),
        ('knn', KNeighborsRegressor())
    ],
    final_estimator=LinearRegression()
)

stack_reg.fit(X_train_reg, y_train_reg)

y_pred_stack_reg = stack_reg.predict(X_test_reg)

print("Stacking R2 Score:", r2_score(y_test_reg, y_pred_stack_reg))

Stacking R2 Score: 0.3166120008255935

# PART : F

In [49]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score

In [50]:
print("Accuracy :", accuracy_score(y_test_cls, y_pred_stack))
print("Precision:", precision_score(y_test_cls, y_pred_stack))
print("Recall   :", recall_score(y_test_cls, y_pred_stack))
print("F1 Score :", f1_score(y_test_cls, y_pred_stack))
print("ROC AUC  :", roc_auc_score(y_test_cls, y_pred_stack))

Accuracy : 0.6682692307692307
Precision: 0.6043478260869565
Recall   : 0.35368956743002544
F1 Score : 0.4462279293739968
ROC AUC  : 0.6065202087536525

In [51]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
import numpy as np

print("MAE :", mean_absolute_error(y_test_reg, y_pred_stack_reg))

print("RMSE :", np.sqrt(mean_squared_error(y_test_reg, y_pred_stack_reg)))

print("R2 Score :", r2_score(y_test_reg, y_pred_stack_reg))

MAE : 9.173290134745326
RMSE : 11.299730771855584
R2 Score : 0.3166120008255935

In [52]:
print("Classification Models")
print("----------------------")
print("Bagging Accuracy :", accuracy_score(y_test_cls, y_pred_cls))
print("AdaBoost Accuracy:", accuracy_score(y_test_cls, y_pred_ada_cls))
print("Gradient Boosting:", accuracy_score(y_test_cls, y_pred_gb_cls))
print("LightGBM Accuracy:", accuracy_score(y_test_cls, y_pred_lgb_cls))
print("XGBoost Accuracy :", accuracy_score(y_test_cls, y_pred_xgb_cls))
print("Voting Accuracy  :", accuracy_score(y_test_cls, y_pred_vote))
print("Stacking Accuracy:", accuracy_score(y_test_cls, y_pred_stack))

Classification Models
----------------------
Bagging Accuracy : 0.6788461538461539
AdaBoost Accuracy: 0.7211538461538461
Gradient Boosting: 0.7153846153846154
LightGBM Accuracy: 0.698076923076923
XGBoost Accuracy : 0.6961538461538461
Voting Accuracy  : 0.6961538461538461
Stacking Accuracy: 0.6682692307692307

In [53]:
print("Regression Models")
print("----------------------")
print("Bagging R2 :", r2_score(y_test_reg, y_pred_reg))
print("AdaBoost R2:", r2_score(y_test_reg, y_pred_ada_reg))
print("Gradient Boosting:", r2_score(y_test_reg, y_pred_gb_reg))
print("LightGBM R2:", r2_score(y_test_reg, y_pred_lgb_reg))
print("XGBoost R2 :", r2_score(y_test_reg, y_pred_xgb_reg))
print("Stacking R2:", r2_score(y_test_reg, y_pred_stack_reg))

Regression Models
----------------------
Bagging R2 : 0.4141829928871321
AdaBoost R2: 0.40470576714874573
Gradient Boosting: 0.48287595365349745
LightGBM R2: 0.4590787156306845
XGBoost R2 : 0.41660021583154216
Stacking R2: 0.3166120008255935

• Bagging reduces variance by combining multiple models.

• Boosting improves weak learners sequentially and generally gives higher accuracy.

• Voting combines predictions from multiple classifiers.

• Stacking uses a meta-model to combine different models and often achieves the best performance.

• Compare the Accuracy (classification) and R² Score (regression). The model with the highest score is considered the best-performing model for the dataset.

# PART : G

Bagging improves model stability.
Boosting improves prediction accuracy by correcting previous mistakes.

AdaBoost is best for beginners.
Gradient Boosting provides balanced performance.
LightGBM is suitable for large datasets.
XGBoost generally provides the best overall performance.

# Voting Ensemble
Combines predictions from multiple models.
Improves prediction accuracy.
Reduces errors from individual models.
Easy to implement.
# Stacking Ensemble
Uses a meta-model to combine multiple models.
Usually achieves higher accuracy than a single model.
Learns from the strengths of different algorithms.
Suitable for complex prediction tasks.

For Classification: Use the model with the highest Accuracy (e.g., XGBoost or Stacking Classifier).

For Regression: Use the model with the highest R² Score (e.g., XGBoost Regressor or Stacking Regressor).

# Final Conclusion

After comparing Bagging, Boosting, Voting, and Stacking models, the best-performing model should be selected based on the evaluation metrics. In most cases, XGBoost and Stacking provide the highest accuracy and R² score, making them the best choices for deployment. They offer strong predictive performance, better generalization, and robust results on unseen data.